const { MavenProject, Dependency } = require('maven');

// Create the Maven project
const project = new MavenProject();

// Configure the build file
project.setGroupId('com.example');
project.setArtifactId(serviceName);
project.setVersion('1.0-SNAPSHOT');
project.setPackaging('jar');
project.setName(serviceName);
project.setDescription('Spring Boot project generated by Yeoman');

// Add dependencies
const dependency = new Dependency();
dependency.setGroupId('org.springframework.boot');
dependency.setArtifactId('spring-boot-starter-web');
dependency.setVersion('2.5.2');
project.addDependency(dependency);

// Generate the pom.xml file content
const pomXmlContent = project.asPom();